driver=nl80211
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
auth_algs=1
wpa_key_mgmt=WPA-PSK
beacon_int=100
ssid=NexusCubeAP
channel=149
# Basic settings
hw_mode=a
# Enable 802.11n/ac
ieee80211d=1
ieee80211n=1
ieee80211ac=1
# Enable 802.11ax
ieee80211ax=1
# HE 802.11ax capabilities
he_su_beamformer=1
he_su_beamformee=1
he_mu_beamformer=1
# BSS color for spatial reuse, value 1-63
he_bss_color=1
he_oper_chwidth=1
# HE/VHT channel widths
he_oper_chwidth=1
vht_oper_chwidth=1
he_oper_centr_freq_seg0_idx=155
vht_oper_centr_freq_seg0_idx=155
# HT 802.11n capabilities
ht_capab=[HT40+][LDPC][SHORT-GI-20][SHORT-GI-40][TX-STBC][RX-STBC1][MAX-AMSDU-7935]
# VHT capabilities 802.11ac
vht_capab=[RXLDPC][SHORT-GI-80][TX-STBC-2BY1][RX-STBC-1][MAX-MPDU-11454][MAX-A-MPDU-LEN-EXP7]
# WMM/QoS
wmm_enabled=1
wpa_passphrase=gregnexus
interface=wlan0
wpa=2
wpa_pairwise=CCMP
country_code=IT
ignore_broadcast_ssid=0